# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    npm install -g newman-reporter-htmlextra
  displayName: 'install newman'
- script: |
    newman run Books.postman_collection.json -e Books_QA.postman_environment.json -r cli,junit,htmlextra --reporter-junit-export "Newman_Junit.xml" --reporter-htmlextra-export "Newman_HTML_Report.html"
  displayName: 'Run Postman Collection'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/Newman_Junit.xml'
    failTaskOnFailedTests: true
    failTaskOnMissingResultsFile: true
    testRunTitle: 'IsraResults'
